# Generated by Django 4.2.16 on 2024-11-23 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peoples', '0003_alter_people_father_alter_people_mother'),
    ]

    operations = [
        migrations.RenameField(
            model_name='people',
            old_name='father',
            new_name='father_id',
        ),
        migrations.RenameField(
            model_name='people',
            old_name='mother',
            new_name='mother_id',
        ),
    ]
